service: faithbranch-website
image: sebastianneiswanger/faithbranch-website
registry:
  username: sebastianneiswanger
  password:
    - KAMAL_REGISTRY_PASSWORD
builder:
  arch: amd64
  secrets:
    - ReSendKey
    - DATABASE_URL
    - NEXTAUTH_SECRET
    - NEXTAUTH_URL
