servers:
  web:
    - 104.131.185.135

env:
  secret:
    - DATABASE_URL
    - ReSendKey
    - NEXTAUTH_SECRET
    - NEXTAUTH_URL

proxy:
  app_port: 3000
  host: faithbranch.com
  ssl: true
  healthcheck:
    path: /up